### ISSUE TITLE
You have example project?

### ISSUE THREAD

**Issue by thepinyo** [Lube/nfc-react-native#2]
I can not get nfc tag. you have any example project?

**Comment by Lube** [comment]
I'll publish an example project on the weekend!

**Comment by Raimmaster** [comment]
Hey, man, I've been trying to adapt my own NFC native module for RN, and failed so far. I foud this project, and it looks awesome, though I can't get it to work, since I'm not really sure how you would implement the methods. Basically, when would you automatically detect if an NFC card had just been approached to the Android device? Any help would be appreciated.

**Comment by Lube** [comment]
In our project we just put the reading/writing functions on a redux saga we trigger with a normal redux action, but you could obviously just trigger one of this functions in a lifecycle hook in some container or component.

In retrospective a EventEmitter api would have been better.

**Comment by mattb2401** [comment]
In the Res folder where do we create the file with this xml 
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
  <tech-list>
    <tech>android.nfc.tech.MifareClassic</tech>
  </tech-list>
</resources>
and what is the name of the file

**Comment by mattb2401** [comment]
In the res folder. where do we place that piece of xml and what is the file name

**Comment by Lube** [comment]
Im working on a update of the lib using event emitters and a sample project, I will publish it near the weekend.

**Comment by Lube** [comment]
Sample project added and API overhaul ready.
